### ISSUE TITLE
rest-json doesn't compile

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus-quickstarts#287]
`mvn clean verify -pl rest-json/` results in `package javax.servlet.http does not exist`

Must be related to latest web layer changes

```
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ rest-json ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /Users/rsvoboda/git/quarkus-quickstarts/rest-json/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/rsvoboda/git/quarkus-quickstarts/rest-json/src/main/java/org/acme/rest/json/LoggingFilter.java:[3,26] package javax.servlet.http does not exist
[ERROR] /Users/rsvoboda/git/quarkus-quickstarts/rest-json/src/main/java/org/acme/rest/json/LoggingFilter.java:[22,5] cannot find symbol
  symbol:   class HttpServletRequest
  location: class org.acme.rest.json.LoggingFilter
[INFO] 2 errors
```

**Comment by rsvoboda** [comment]
@gsmet fyi, this will be probably noteworthy item for end users so they can adjust their dependencies.

**Comment by machi1990** [comment]
I suppose this is after https://github.com/quarkusio/quarkus/pull/4052 was merged ?

**Comment by gsmet** [comment]
I know about this. Please don’t merge anything master specific for now as mentioned on the list. 

The quick starts need to work with the 0.23 branch.

**Comment by gsmet** [comment]
See this discussion on Zulip I started yesterday: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Life.20without.20Undertow

**Comment by gsmet** [comment]
I created https://github.com/quarkusio/quarkus/issues/4125 .
